repeat_experiment:                  1
ctx:                                'autoencoder_regcomp_robust_fctdist'
mode:                               ['test']
test_models:                        './models/trained_models/reprod/dsaa/autoencoder_regcomp_robust_fctdist'
dataset:                            Null
algorithm:                          Null
evaluations:                        [
  'marabou_robust',
  'marabou_largest_error'
]
