repeat_experiment:                  10
ctx:                                'autoencoder_gaussian_fctdist'
mode:                               ['train']
test_models:                        Null
dataset:                            'gaussianClouds'
algorithm:                          'autoencoder'
evaluations:                        []


datasets:
    subsample:                      Null
    num_samples:                    1000
    synthetic_test_samples:         10000
    scale:                          False
    sineNoise:
        file_path:                  Null
        num_anomalies:              0
        spacedim:                   30
    gaussianClouds:
        # Note that this folder should point to the three data files
        file_path:                  './datasets/synthetic/gaussianClouds/fct_dist_2d'
    proximalPhalanxOutlineCorrect:
        file_path:                  Null
    sonyAIBORobotSurface1:
        file_path:                  Null
    sonyAIBORobotSurface2:
        file_path:                  Null
    twoLeadEcg:
        file_path:                  Null
    moteStrain:
        file_path:                  Null

algorithms:
    num_epochs:                     50
    lr:                             1e-3
    autoencoder:
        robust_ae:                  0.0
        denoising:                  0.0
        fct_dist:                   ['mat', 'bias'] # ('mat', 'bias', 'relu')
        lambda_fct:                 0.0001
        border_dist:                False
        lambda_border:              0.001
        penal_dist:                 Null
        dropout:                    False
        L2Reg:                      0.0000
        topology:                   [2,15,30,50,30,15,2]
        bias:                       True
        num_border_points:          5
