repeat_experiment:                  2
ctx:                                'autoencoder_uniform_2D'
mode:                               ['train']
test_models:                        Null
dataset:                            'sineNoise'
algorithm:                          'autoencoder'
evaluations:                        []


datasets:
    subsample:                      Null
    num_samples:                    1000
    synthetic_test_samples:         10000
    scale:                          False
    sineNoise:
        #file_path:                  './datasets/synthetic/sineNoise/60'
        file_path:                  Null
          #num_samples:                1000
        num_anomalies:              0
        spacedim:                   2
    mnist:
        file_path:                  Null
          #num_samples:                35000
        num_anomalies:              0
        normal_class:               7
    cardio:
        file_path:                  Null
        num_anomalies:              0
    pc3:
        file_path:                  Null
        num_anomalies:              0
    wafer:
        file_path:                  Null
        num_anomalies:              0
    steel_plates_fault:
        file_path:                  Null
        num_anomalies:              0
    qsar_biodeg:
        file_path:                  Null
        num_anomalies:              0
    page_blocks:
        file_path:                  Null
        num_anomalies:              0
    ozone_level_8hr:
        file_path:                  Null
        num_anomalies:              0
    gas_drift:
        file_path:                  Null
        num_anomalies:              0
    har:
        file_path:                  Null
        num_anomalies:              0
    ionosphere:
        file_path:                  Null
        num_anomalies:              0
    satellite:
        file_path:                  Null
        num_anomalies:              0
    segment:
        file_path:                  Null
        num_anomalies:              0
    wbc:
        file_path:                  Null
        num_anomalies:              0
    satimage:
        file_path:                  Null
        num_anomalies:              0
    electricDevices:
        file_path:                  Null
    italyPowerDemand:
        file_path:                  Null
    ecg5000:
        file_path:                  Null
    proximalPhalanxOutlineCorrect:
        file_path:                  Null
    sonyAIBORobotSurface1:
        file_path:                  Null
    sonyAIBORobotSurface2:
        file_path:                  Null
    syntheticControl:
        file_path:                  Null
    twoLeadEcg:
        file_path:                  Null
    chinatown:
        file_path:                  Null
    crop:
        file_path:                  Null
        class1:                     4
        class2:                     12
    moteStrain:
        file_path:                  Null
    melbournePedestrian:
        file_path:                  Null

algorithms:
    num_epochs:                     5
    lr:                             1e-3
    autoencoder:
        robust_ae:                  0.0
        denoising:                  0.0
        fct_dist:                   [] # ('mat', 'bias', 'relu')
        lambda_fct:                 0.0001
        border_dist:                False
        lambda_border:              0.001
        penal_dist:                 Null
        dropout:                    False
        L2Reg:                      0.0000
        topology:                   [2,15,30,50,30,15,2]
        bias:                       True
        num_border_points:          5
