repeat_experiment:                  1
ctx:                                'simon_dean_wbc_0'
mode:                               ['test']
test_models:                        './models/trained_models/simon_dean_wbc'
dataset:                            Null
algorithm:                          Null
evaluations:                        [
    'marabou_ens_normal_rob',
    #    'marabou_ens_normal_rob_ae',
    #    'marabou_svdd_normal_rob',
    #    'downstream_naiveBayes',
    #    'downstream_knn',
    #    'downstream_rf',
    #    'inst_area_2d_plot',
    #    'marabou_robust',
    #    'marabou_largest_error',
]
